server:
  port: 8080

# Spring
spring:
  application:
    # 应用名称
    name: coriander-system
  profiles:
    # 环境配置
    active: dev
    include: mysql,redis,sa-token

# mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  type-aliases-package: com.coriander.system.domain.pojo          # 所有POJO类所在包路径

# 日志的方式打印sql
logging:
  level:
    com.coriander.system.mapper: DEBUG
